### ISSUE TITLE
Setup trouble with miniconda2 (using the root environment)

### ISSUE THREAD

**Issue by maxseidler** [mandeep/sublime-text-conda#1]
After installing sublime-text-conda, the Package Control Message says:
>  sublime-text-conda assumes that conda can be found in Anaconda's default install path.
  If the install path was changed when installing Anaconda or if you're using Miniconda,
  sublime-text-conda's settings will need to be changed in
  Preferences -> Package Settings -> Conda

So made the following changes in the conda.sublime user settings:
```
{
    "executable": "/Applications/miniconda2/bin/python2.7",
    "environment_directory": "/Applications/miniconda2/envs"
}
```

'Conda' is selected as the Build System. But running any `Conda` command from the Sublime Text Command Palette only results in the error message `No Active Conda Environment`

### Things I have tried:
1. Verifying that the file paths stated above are correct
2. Setting up a Conda Enviroment (cloned root) and activated it

Whatever I tried I only get a `No Active Conda Environment` message. I did extensive googling but couldn't find anything on this issue, so its probably my fault. I am out of my wit though.

**Comment by mandeep** [comment]
Thanks for reporting this and sorry to hear about your troubles. Could you show me the result of running ``conda info`` in terminal?

**Comment by maxseidler** [comment]
Thanks for the response. Here is the result of running `conda info` in the terminal:

```
Current conda install:

               platform : osx-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /Applications/miniconda2  (writable)
    default environment : /Applications/miniconda2
       envs directories : /Applications/miniconda2/envs
                          /Users/Max/.conda/envs
          package cache : /Applications/miniconda2/pkgs
                          /Users/Max/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.24 requests/2.14.2 CPython/2.7.13 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

```

**Comment by mandeep** [comment]
Nothing seems out of the ordinary. When you try ``Conda: Create Environment``, is there any output in the debug console? You can access this console on the menu bar via View -> Show Console.

**Comment by maxseidler** [comment]
Oh, interesting. I was able to `create` a new Conda environment via Sublime. And when I executed `Conda: Activate Environment` it showed me the newly created and the environment from yesterday, so it definitely knows where to look. After activation I was able to `Conda: List Packages`, etc.

I only wonder if it is possible to work with the root environment since that is the only one I am actually using. Can I somehow `activate` the root environment?

Thank you for your kind help so far.

**Comment by mandeep** [comment]
Currently only created conda environments are available for use. I'll start working on a new release that includes the root environment. Hopefully I can tag a new release later today.

**Comment by maxseidler** [comment]
Awesome, thank you very much.

**Comment by mandeep** [comment]
@maxseidler I've tagged a new release of sublime-text-conda that adds the root environment as an environment that is able to be activated. Package Control should automatically update your package shortly. Please let me know if you run into any issues using it. 😃

**Comment by maxseidler** [comment]
Very cool, thank you for this update!

**Comment by mandeep** [comment]
No problem!
