### ISSUE TITLE
Can't setup conda

### ISSUE THREAD

**Issue by Frinzie** [mandeep/sublime-text-conda#11]
I set up the settings like this: 

> {
> 	"executable": "C:/MiniConda/python",
> 	"environment_directory": "C:/MiniConda/envs",
> 	"configuration": "C:/Users/Jan L/.condarc",
> }

but when I try to build with conda I get this output 

>  __init__() got an unexpected keyword argument 'cancel'
> [cmd: ['C:\\MiniConda\\envs\\arst\\python', '-u', 'D:\\Pulpit\\scrit.py']]
> [dir: D:\Pulpit]
> [path: C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Sublime Text 3;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\MiniConda;C:\MiniConda\Scripts;C:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseGit\bin;C:\Users\Jan L\AppData\Local\Microsoft\WindowsApps;C:\Users\Jan L\AppData\Roaming\npm;]
> [Finished]

The plugin also doesn't recognize the environments, nor the packages from my miniconda. What do i do?

**Comment by mandeep** [comment]
Hi @Frinzie,  thanks for the report. Can you show me the output of `conda info`?
