### ISSUE TITLE
path to base environment is incorrect

### ISSUE THREAD

**Issue by spfeifer222** [mandeep/sublime-text-conda#19]
Dear mandeep,

I love your package, but I cant get the base environment working in sublime. In Strg+P - conda: activate environment, the base (there called ROOT) enviroment path is incorrect:

`/home/my_name//miniconda` instead of

`/home/my_name/bin/miniconda`.

Where does the package get the information from? 

Best regards,
Sebastian

**Comment by mandeep** [comment]
Hi @spfeifer222 sorry for the delayed response. 

Are you saying that even when changing the user settings in `Preferences->Package Settings->Conda` that you're unable to build?

**Comment by spfeifer222** [comment]
Hi mandeep, 

No problem. I identified and solved the problem:

My miniconda path is set to ` "executable": "~/bin/miniconda/bin/python3"`. The line No. 51 in your commands.py replace both appearances of `bin`.

You could replace this line with 

`root_directory = os.path.dirname(self.executable).rstrip('bin')` 

in order to remove the last `bin` only.

By the way: How about renaming `root` environment to `base`? This would be consistent with the `miniconda` naming. 

`

**Comment by mandeep** [comment]
Thanks for letting me know! I'll push a fix for both issues.

**Comment by mandeep** [comment]
fixed by 0128fb1859ea83ed6f8740e0bd8334c11d6d5183

**Comment by spfeifer222** [comment]
Am Freitag, den 20.03.2020, 11:26 -0700 schrieb Mandeep Bhutani:
> Closed #19.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks a lot!
