### ISSUE TITLE
Cancel build has no effect

### ISSUE THREAD

**Issue by cgarrard** [mandeep/sublime-text-conda#2]
It would be great if the Cancel Build command worked while building with Conda, but it doesn't seem to. Is it possible to enable this?

**Comment by mandeep** [comment]
Hi @cgarrard! Unfortunately this is a problem with the way Sublime's Default.exec.ExecCommand handles inheritance: https://github.com/mandeep/sublime-text-conda/blob/509ef877d6ddc1506333db024043366549d9946d/commands.py#L425

I've mentioned this before on sublime's IRC channel awhile ago but nothing really came out of it. I'll try discussing this again to see if there have been any new changes.

**Comment by cgarrard** [comment]
I was afraid it might be something like this. Thanks for responding and
looking into it!

On Sep 5, 2017 9:28 PM, "Mandeep Bhutani" <notifications@github.com> wrote:

Hi @cgarrard <https://github.com/cgarrard>! Unfortunately this is a problem
with the way the sublime execute command handles inheritance.
https://github.com/mandeep/sublime-text-conda/blob/509ef877d
6ddc1506333db024043366549d9946d/commands.py#L425

I've mentioned this before on sublime's IRC channel awhile ago but nothing
really came out of it. I'll try discussing this again to see if there's
been any new changes.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mandeep/sublime-text-conda/issues/2#issuecomment-327364273>,
or mute the thread

**Comment by mandeep** [comment]
@cgarrard,

Turns out the solution to this issue was pretty simple. I've released version 0.4.0 of sublime-text-conda that will allow you to use the ``Cancel Build`` option in Sublime Text. Package Control should automatically update your version shortly.

Please let me know if you have further issues.

**Comment by cgarrard** [comment]
You're awesome, @mandeep! Thanks!

**Comment by mandeep** [comment]
No problem :smiley:

**Comment by koenvanderleij** [comment]
I still encounter this problem, how should I fix this?

**Comment by mandeep** [comment]
@koen430 Could you let me know what operating system you're using as well as which version of sublime-text-conda you're running?

**Comment by koenvanderleij** [comment]
@mandeep Thanks for the quick response! I am running on Mac, the version of sublime-text-conda that I am using is v0.5.0

**Comment by mandeep** [comment]
Thanks. I'm able to replicate this issue with ST v3.1.1 Build 3176. Are you running the same build?

**Comment by koenvanderleij** [comment]
Yes, that is the build I am running

**Comment by mandeep** [comment]
I'm thinking this is a problem with ST3. I will investigate and see if there is anything I can do to mitigate this.

**Comment by mandeep** [comment]
@koen430 It seems that there were some internal changes to ST3 that broke sublime-text-conda's way of canceling a build. I've pushed a fix for this in v0.5.1. Please let me know if you still experience this issue after upgrading.

**Comment by koenvanderleij** [comment]
Thank you very much! Works perfectly fine now
