### ISSUE TITLE
Document the run_through_shell and use_pythonw optons

### ISSUE THREAD

**Issue by msiniscalchi** [mandeep/sublime-text-conda#21]
Please mention these options in the README file. I lost a bunch of time trying to produce a plot (with no output or error) until I opened the settings file on github.... thank you!

**Comment by mandeep** [comment]
Hi @msiniscalchi sorry about the time wasted figuring things out. I'll submit a PR with better documentation in the readme.

**Comment by msiniscalchi** [comment]
No worries @mandeep . Thanks for the awesome plugin!

**Comment by mandeep** [comment]
Fixed by fb594499aabb7fea8faa6299330850dc940e5051
