### ISSUE TITLE
Settings are get from wrong path and not found (manually installed)

### ISSUE THREAD

**Issue by zap-wizard** [mandeep/sublime-text-conda#25]
Manually installed this package with `git clone`, and then moved it to Sublime Text's Packages-folder.  When I went to Preferences -> Package Settings -> Conda -> Settings I got an error like this:
`The settings file "res://Packages/Conda/Conda (OSX).sublime-settings" could not be opened`

It seems like Sublime tried to get the settings from `Packages/Conda`, but the package is in `Packages/sublime-text-conda`. I changed the name of the folder to Conda an now it's working fine.

So problem solved, but posted for letting others know.

Sublime Text 3.2.2
OS X High Sierra

**Comment by mandeep** [comment]
Thanks for opening an issue. You were right to change the directory name from sublime-text-conda to Conda. This is an issue with cloning the repository versus downloading the package via Package Control. I'll add some documentation to the readme to make this clear.

**Comment by mandeep** [comment]
Fixed by commit f9e92627e0b6634cb585f0ce5a3f1d2387e40c1a
