### ISSUE TITLE
code not run

### ISSUE THREAD

**Issue by sachinwalunjakar** [mandeep/sublime-text-conda#31]
I am new to sublime text editor  and I trying to run python kivy app and for that purpose I installed package conda in sublime.
         But when I press "ctrl + b" code not get execute.
I have installed anaconda on  window.
I don't no have solve this problem.
Please help !!

**Comment by mandeep** [comment]
Did you follow the directions in the README?

**Comment by mandeep** [comment]
Hi @sachinwalunjakar. I'm closing this issue for now. Please let me know if you're still having issues. I'll be happy to help.
