### ISSUE TITLE
Anaconda Not in Default Directory

### ISSUE THREAD

**Issue by Zoher15** [mandeep/sublime-text-conda#5]
![image](https://user-images.githubusercontent.com/29090730/35784762-1a541d10-09e9-11e8-8b3a-d51f5dc6a521.png)
How exactly do I need to  configure the user package settings for Conda?

**Comment by mandeep** [comment]
On the Sublime Text toolbar go to Preferences->Package Settings->Conda->Settings - User.

Change the values in that file to the location of your install. If the user settings file is empty, copy the contents from Settings - Default into Settings - User and then change the values.

**Comment by Zoher15** [comment]
Hey Mandeep, that was my initial intuition and that is exactly what I had done. But I had errors while importing packages like NLTK that were already installed. Do you have any suggestions?

**Comment by mandeep** [comment]
Could you show me what kind of errors you're getting? With the paths in the settings file changed, you would then need to activate the root environment or another conda environment via the ``Conda: Activate`` command.

**Comment by Zoher15** [comment]
![image](https://user-images.githubusercontent.com/29090730/35832267-a94de17a-0a9a-11e8-8bb0-571892df7089.png)


![image](https://user-images.githubusercontent.com/29090730/35832282-b82b2928-0a9a-11e8-9aa5-58c043565c3b.png)

![image](https://user-images.githubusercontent.com/29090730/35832306-ca43fb76-0a9a-11e8-8486-9ea33a6cc6d3.png)

**Comment by mandeep** [comment]
Is the ``Conda`` build system selected in Tools->Build System?

**Comment by Zoher15** [comment]
Yes Mandeep

**Comment by Zoher15** [comment]
Is something wrong with my custom path?

**Comment by mandeep** [comment]
Your directory is ``C:\Users\zoya\Anaconda2`` but the directory in settings is listed as ``~/anaconda2/``. I'm not familiar with how Windows handles filenames but does the plugin work if you capitalize the A in the anaconda2 path?

**Comment by Zoher15** [comment]
I tried capitalizing as well as entering the entire path

**Comment by Zoher15** [comment]
I even installed nltk using conda just to check. Did not work. I cant find an .condarc file for some reason

**Comment by mandeep** [comment]
If you write ``import sys`` in a Python file and ``print(sys.executable)`` does the correct path show? Are you able to import any other packages in your environment? According to your conda info screenshot your config file is in ``C:\Users\zoya\.condarc``, however I don't think it matters in this case .I'm unable to replicate this which is why I'm trying to see what exactly could be causing this on your system.

**Comment by Zoher15** [comment]
It goes to C:\Python27\python.exe

despite setting my user settings as
// Default settings for sublime-text-conda:
{
    // executable is the path to anaconda's python
    // this python executable is used in order to find conda
    "executable": "C:\\Users\\zoya\\Anaconda2",

    // Directory in which the conda envs are stored
    // Default location is the user's home directory
    "environment_directory": "C:\\Users\\zoya\\Anaconda2\\envs",

    // configuration is the path to conda's configuration file
    "configuration": "~/.condarc"
}

**Comment by mandeep** [comment]
So we've narrowed it down to the path. When you open the command palette and select ``Conda: Activate Environment`` are you able to select your environment? If so, does anything appear in the status bar after selecting the env?

**Comment by Zoher15** [comment]
Yes on doing all of the steps again I fixed it to the right path and was able to activate it. It is working now!

Thank you for your patience Mandeep  👍 Really appreciate your promptness :)

best,
Zoher

**Comment by mandeep** [comment]
Glad everything worked out! 👍
