### ISSUE TITLE
Where is Conda.sublime-build installing from Package Control?

### ISSUE THREAD

**Issue by marnunez** [mandeep/sublime-text-conda#6]
Under windows, I have to add `shell: true` to Conda.sublime-build to make matplotlib show the plots.
Installing through git, no problem at all.
Installing through Package Control, can't find Conda.sublime-build anywhere.

**Comment by mandeep** [comment]
When installed via Package Control, the sublime-build file will be located in ``C:\Users\username\AppData\Roaming\Sublime Text 3\Installed Packages``. Let me know if you don't find it there.
