### ISSUE TITLE
Renaming caused macOS 10.13 to not load old user configuration

### ISSUE THREAD

**Issue by mys721tx** [mandeep/sublime-text-conda#7]
The following line caused macOS 10.13 not to load the old user configuration file as Python's `open()` is case sensitive.

https://github.com/mandeep/sublime-text-conda/blob/44095806ae1f6b12e8f8a0f5f50eeb22ea355864/commands.py#L20

Since HFS+ and AFPS by default are case-insensitive, deleting and recreating the file will solve the problem.

**Comment by mandeep** [comment]
Thanks for pointing this out. I believe conda.sublime-settings was changed to uppercase in a previous bugfix. I'll have to think about whether or not I want to change it back to lowercase, or just add another line to check for both files.

**Comment by mandeep** [comment]
@mys721tx thanks again for letting me know about this. I've pushed a fix that should address this.
